### ISSUE TITLE
Dimension wrong in metric drawing

### ISSUE THREAD

**Issue by jan-harm** [fsmMLK/inkscapeDimensions#19] opened 2022-08-12 14:38 UTC
Hi
I created an new document on A4 (297 x 210 mm) with scale 1.0 so the viewbox is the same (297 x 210).
Then I draw a box and a line to have the dimensions. 
Rather then drawing 2 cm on the 2 cm line it annotates with  0.53 cm
(scale is 1.0 and unit is cm)
Is this an error or do I overlook something?
regards 
![image](https://user-images.githubusercontent.com/16928059/184375364-6982cd15-49c0-4b4c-9cad-f2dd15e22c66.png)

**Comment by rm-greenzie** [comment] 2022-08-24 17:08
duplicate of #6

**Closed as completed** 2024-12-25 12:44 UTC
